# --- 1. Load Required Libraries ---
# Make sure you have these libraries installed. If not, uncomment and run:
# install.packages("data.table")
# install.packages("dplyr")
# install.packages("tibble")
# install.packages("ggplot2")
# install.packages("tidyr") # For gather() function used in plotting

library(data.table) # For efficient reading of large files
library(dplyr)      # For data manipulation
library(tibble)     # For converting row names to a column
library(ggplot2)    # For plotting
library(tidyr)      # For data tidying for plotting

# --- 2. Set Working Directory (Optional but Recommended) ---
# Set this to the directory where your input files (cluster assignments, expression data)
# and the new GPy smoothed means file are located, and where you want the output .rnk and .pdf files to be saved.
setwd("~/Desktop/dpgp_gsea/corr rank") # REMEMBER TO CHANGE THIS TO YOUR ACTUAL DIRECTORY

# --- 3. Load Data ---

# Load the cluster assignments file
cluster_assignments_df <- fread("mus_means_±2fc_results_optimal_clustering.txt", sep = "\t", data.table = FALSE)

# Load the normalized expression values file
expression_df <- fread("mus_means_2fc.txt", sep = "\t", data.table = FALSE, header = T)
# Set the first column ('gene_id') as row names
expression_df <- tibble::column_to_rownames(expression_df, var = "symbol")

# Define time point labels and their numeric mapping
time_point_labels <- c("0dpi", "3dpi", "7dpi", "14dpi", "21dpi")
time_numeric_map <- setNames(c(0, 3, 7, 14, 21), time_point_labels)
colnames(expression_df) <- time_point_labels # Ensure expression_df has these column names

# --- NEW: Load the GPy smoothed means exported from Python ---
# IMPORTANT: Replace "aco_means_±2fc_results_cluster_GPy_smoothed_means.tsv"
# with the exact filename generated by your Python script.
# This file name depends on the 'args.output_path_prefix' you used when running DP_GP_cluster.py
smoothed_means_from_gpy <- fread("mus_means_±2fc_results_cluster_GPy_smoothed_means.tsv", sep = "\t", data.table = FALSE)


# --- 4. Prepare for Ranking ---
ranked_genes_by_cluster <- list()
unique_clusters <- sort(unique(cluster_assignments_df$cluster))

# --- 5. Iterate Through Each Cluster, Calculate Mean, and Rank Genes ---
for (cluster_id in unique_clusters) {
  cat(paste0("Processing Cluster ", cluster_id, "...\n"))
  
  genes_in_cluster <- cluster_assignments_df$gene[cluster_assignments_df$cluster == cluster_id]
  cluster_expression_data <- expression_df[rownames(expression_df) %in% genes_in_cluster, ]
  
  if (nrow(cluster_expression_data) == 0) {
    cat(paste0("  Warning: No expression data found for genes in Cluster ", cluster_id, ". Skipping.\n"))
    next
  }
  
  # Mean-center individual genes
  # This ensures that each gene's profile is centered around zero,
  # allowing correlation to focus on shape rather than absolute magnitude.
  mean_centered_cluster_expression_data <- t(apply(cluster_expression_data, 1, function(x) x - mean(x)))
  colnames(mean_centered_cluster_expression_data) <- colnames(cluster_expression_data)
  
  # --- MODIFIED: Retrieve the GPy smoothed mean for the current cluster ---
  # Filter the loaded GPy smoothed means for the current cluster
  current_cluster_gpy_smoothed_mean_df <- smoothed_means_from_gpy %>%
    filter(ClusterID == cluster_id) %>%
    # Select columns corresponding to time points in the correct order
    select(paste0(time_point_labels, "_SmoothedMean"))
  
  # Convert to a numeric vector for correlation calculation
  smoothed_cluster_mean_for_correlation <- as.numeric(current_cluster_gpy_smoothed_mean_df[1,])
  
  # Check if GPy smoothed mean data is valid
  if (length(smoothed_cluster_mean_for_correlation) == 0 || all(is.na(smoothed_cluster_mean_for_correlation))) {
    cat(paste0("  Warning: No GPy smoothed mean found for Cluster ", cluster_id, ". Skipping correlation for this cluster.\n"))
    next
  }
  
  # d. Calculate the Pearson correlation for each gene in the cluster to the GPy SMOOTHED cluster mean
  correlations_df <- data.frame(Gene = character(), Correlation_Score = numeric(), stringsAsFactors = FALSE)
  
  for (i in 1:nrow(mean_centered_cluster_expression_data)) {
    gene_symbol <- rownames(mean_centered_cluster_expression_data)[i]
    gene_expression_profile <- as.numeric(mean_centered_cluster_expression_data[i, ])
    
    # Handle cases where standard deviation is zero (e.g., constant gene expression or constant mean)
    if (sd(gene_expression_profile) == 0 || sd(smoothed_cluster_mean_for_correlation) == 0) {
      correlation_score <- -2 # Assign a very low score if correlation cannot be computed
      cat(paste0("  Warning: Standard deviation is zero for gene ", gene_symbol, " or GPy smoothed cluster mean in Cluster ", cluster_id, ". Assigning low correlation score.\n"))
    } else {
      correlation_score <- cor(gene_expression_profile, smoothed_cluster_mean_for_correlation, method = "pearson")
    }
    correlations_df <- rbind(correlations_df, data.frame(Gene = gene_symbol, Correlation_Score = correlation_score, stringsAsFactors = FALSE))
  }
  
  # e. Rank the genes within the cluster by correlation in descending order
  ranked_cluster_df <- correlations_df %>%
    arrange(desc(Correlation_Score))
  
  # f. Store the ranked list in our main list
  ranked_genes_by_cluster[[paste0("Cluster_", cluster_id)]] <- ranked_cluster_df
  
  # --- 6. Save Ranked List to .rnk File for GSEA ---
  # GSEA .rnk files are tab-delimited with no header and two columns (Gene, Score)
  output_filename_rnk <- paste0("Cluster_", cluster_id, "_ranked_genes_GPy_smoothed.rnk")
  write.table(ranked_cluster_df,
              file = output_filename_rnk,
              sep = "\t",
              row.names = FALSE,  # Do not write row names
              col.names = FALSE,  # Do not write column names (header)
              quote = FALSE       # Do not put quotes around strings
  )
  cat(paste0("Saved: ", output_filename_rnk, "\n"))
  
  # --- 7. Plotting Mean-Centered Gene Expression and GPy SMOOTHED Cluster Mean ---
  # Prepare data for ggplot2
  
  # Convert time_points_numeric (from Python export) to a named R vector for consistency
  # This ensures plotting points align with the x-axis labels
  
  plot_data_smoothed_mean <- data.frame(Time_Numeric = as.numeric(time_numeric_map),
                                        Expression = smoothed_cluster_mean_for_correlation,
                                        Type = "GPy Smoothed Cluster Mean")
  
  # Prepare individual gene expression data for plotting
  plot_data_genes <- as.data.frame(mean_centered_cluster_expression_data)
  plot_data_genes$Gene <- rownames(plot_data_genes)
  plot_data_genes_long <- tidyr::gather(plot_data_genes, Time_Label, Expression, -Gene)
  plot_data_genes_long$Time_Numeric <- time_numeric_map[plot_data_genes_long$Time_Label]
  
  plot_title <- paste0("Cluster ", cluster_id, " - Mean Centered Gene Expression and GPy Smoothed Cluster Mean")
  plot_filename_pdf <- paste0("Cluster_", cluster_id, "_mean_centered_GPy_smoothed_expression_plot.pdf")
  
  p <- ggplot() +
    geom_line(data = plot_data_genes_long, aes(x = Time_Numeric, y = Expression, group = Gene), color = "red", alpha = 0.3) +
    geom_line(data = plot_data_smoothed_mean, aes(x = Time_Numeric, y = Expression, group = Type), color = "blue", linewidth = 1.5) +
    labs(title = plot_title, x = "Time Point", y = "Mean Centered Expression") +
    theme_minimal() +
    theme(plot.title = element_text(hjust = 0.5)) +
    scale_x_continuous(breaks = as.numeric(time_numeric_map), labels = time_point_labels) +
    scale_y_continuous(limits = c(-3,3))
  
  ggsave(plot_filename_pdf, plot = p, width = 8, height = 6)
  cat(paste0("Saved plot: ", plot_filename_pdf, "\n"))
}

# --- 8. Optional: Display Top 5 Genes for Each Cluster ---
cat("\n--- Top 5 Ranked Genes for Each Cluster ---\n")
for (cluster_name in names(ranked_genes_by_cluster)) {
  cat(paste0("\n", cluster_name, ":\n"))
  print(head(ranked_genes_by_cluster[[cluster_name]], 5))
}
